<?php

namespace Admin\EinstitutAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionDiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionDiplomeRepository extends EntityRepository
{
}
