<?php

namespace Admin\EinstitutAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionModuleRepository extends EntityRepository
{
}
